%%%%%%%% DEFAULT EDGE UTILITY %%%%%%%%
% TYPE: 
% MULTI-TENANCY: OFF
% DETAILS: ASSIGNS RESOURCES TO USERS BASED ON THEIR ACHIEVABLE RATES AND 
% UTILITY FUNCTIONS. THE UTILITY FUNCTION IS UNITLESS AND CAN BE CUSTOMIZED
% ACCORDING TO THE SCENARIO
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function Default_EdgeUtilityFunction()



end